// <auto-generated />
using System;
using MarketPulse.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarketPulse.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260720104401_RemoveMarketPriceSeedData")]
    partial class RemoveMarketPriceSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarketPulse.Api.Models.FinancialInstrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Instruments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Currency = "USD",
                            Exchange = "NASDAQ",
                            IsActive = true,
                            Name = "Apple Inc.",
                            Ticker = "AAPL"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Currency = "USD",
                            Exchange = "NASDAQ",
                            IsActive = true,
                            Name = "Microsoft Corporation",
                            Ticker = "MSFT"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Currency = "USD",
                            Exchange = "NASDAQ",
                            IsActive = true,
                            Name = "NVIDIA Corporation",
                            Ticker = "NVDA"
                        });
                });

            modelBuilder.Entity("MarketPulse.Api.Models.MarketPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ClosePrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("FinancialInstrumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FinancialInstrumentId", "TimestampUtc")
                        .IsUnique();

                    b.ToTable("MarketPrices", (string)null);
                });

            modelBuilder.Entity("MarketPulse.Api.Models.MarketPrice", b =>
                {
                    b.HasOne("MarketPulse.Api.Models.FinancialInstrument", "FinancialInstrument")
                        .WithMany("Prices")
                        .HasForeignKey("FinancialInstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinancialInstrument");
                });

            modelBuilder.Entity("MarketPulse.Api.Models.FinancialInstrument", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
